# Номер порта сервера
# По умолчанию: 8080
port: 9090
# Список включенных функций
features:
- feature1
- feature2
- feature3
- new-feature
# Включить режим отладки для подробного логирования
debugMode: true
database:
  # Адрес хоста базы данных
  host: localhost
  # Номер порта базы данных
  port: 3306
